pluginManagement {
    repositories {
        maven {
            name = 'Forge'
            url = 'https://maven.minecraftforge.net/'
        }
        maven {
            name = 'Stonecutter'
            url = "https://maven.kikugie.dev"
        }
        maven {
            name = 'KikuGie Releases'
            url = "https://maven.kikugie.dev/releases"
        }
        gradlePluginPortal()
        mavenCentral()
    }
}

plugins {
    id "dev.kikugie.stonecutter" version "0.7.10"
}

stonecutter {
    create(rootProject) {
        vers("26.1.2-fabric", "26.1.2")
        vers("1.20.1-forge", "1.20.1")
        vcsVersion = "26.1.2-fabric"
    }
}