modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="spatial_gui"
version="${version}"
displayName="Spatial GUI"
logoFile="assets/spatial-gui/icon.png"
description='''
A client-side mod that renders inventory & container screens as a 3D plane.
'''

[[mixins]]
config="spatial-gui.mixins.json"

[[dependencies.spatial_gui]]
modId="forge"
mandatory=true
versionRange="[47.4.0,48)"
ordering="NONE"
side="CLIENT"

[[dependencies.spatial_gui]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.20.2)"
ordering="NONE"
side="CLIENT"

[[dependencies.spatial_gui]]
modId="cloth_config"
mandatory=true
versionRange="[11.1.0,12)"
ordering="NONE"
side="CLIENT"
